version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: moneyfollow-postgres
    environment:
      POSTGRES_DB: moneyfollow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moneyfollow-network

  backend:
    build: ./backend
    container_name: moneyfollow-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/moneyfollow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - moneyfollow-network

volumes:
  postgres_data:

networks:
  moneyfollow-network:
    driver: bridge
